[package]
name = "subtensor-linting"
version = "0.1.0"
edition = "2024"

[dependencies]
syn.workspace = true
quote.workspace = true
proc-macro2.workspace = true
procedural-fork.workspace = true

[lints]
workspace = true
