[package]
name = "procedural-fork"
version = "1.10.0-rc3"
edition.workspace = true

[lints.clippy]
all = "allow"

[dependencies]
derive-syn-parse.workspace = true
Inflector.workspace = true
cfg-expr.workspace = true
itertools.workspace = true
proc-macro2.workspace = true
quote.workspace = true
syn = { workspace = true, features = [
    "full",
    "visit-mut",
    "visit",
    "extra-traits",
    "parsing",
] }
macro_magic = { workspace = true, features = ["proc_support"] }
frame-support-procedural-tools.workspace = true
proc-macro-warning.workspace = true
expander.workspace = true
sp-crypto-hashing.workspace = true

[dev-dependencies]
regex.workspace = true

[features]
default = ["std"]
std = ["sp-crypto-hashing/std", "regex/std"]
no-metadata-docs = []
experimental = []
# Generate impl-trait for tuples with the given number of tuples. Will be needed as the number of
# pallets in a runtime grows. Does increase the compile time!
tuples-96 = []
tuples-128 = []
