"""Generate the docs reference section from the SDK's own registries.

Everything under docs/tx, docs/query, docs/errors, and the hyperparameters
index/meta (in the repo-root docs folder) plus public/catalog/ is emitted by
this script — never hand-edited (the per-hyperparameter explainer pages in
docs/hyperparameters/ are hand-written; --check verifies one exists per
parameter). The inputs are the same registries that generate the CLI
(`bittensor.intents.REGISTRY`, `bittensor.reads.REGISTRY`), the error taxonomy
(`bittensor.error_map`, `bittensor.result`), and the hyperparameter semantics
table (`bittensor.hyperparams`), so the docs cannot drift from the code.

Usage (from sdk/python, whose environment provides the bittensor SDK):

    uv run python ../../website/apps/bittensor-website/scripts/generate.py            # regenerate in place
    uv run python ../../website/apps/bittensor-website/scripts/generate.py --check    # exit 1 if committed output is stale
"""

from __future__ import annotations

import argparse
import filecmp
import functools
import inspect
import json
import re
import shutil
import sys
import tempfile
import textwrap
from dataclasses import MISSING, fields
from pathlib import Path

from bittensor import error_descriptions, error_map, hyperparams, result
from bittensor._generated.errors import ERRORS as CHAIN_ERROR_CATALOG
from bittensor.intents import REGISTRY as INTENTS
from bittensor.intents.hyperparameters import OWNER_HYPERPARAMETERS
from bittensor.intents.registry import list_tools
from bittensor.namespaces import NAMESPACES
from bittensor.reads import REGISTRY as READS
from bittensor.reads import list_reads

# Read category -> `client.<attr>` namespace carrying that category's reads.
NAMESPACE_ATTR = {cls._category: attr for attr, cls in NAMESPACES.items()}

APP_DIR = Path(__file__).resolve().parent.parent
# Docs content lives at the repository root (subtensor/docs), shared with the
# in-repo contributor docs; see source.config.ts.
CONTENT = APP_DIR.parents[2] / "docs"
CATALOG = APP_DIR / "public" / "catalog"

GENERATED_NOTE = (
    "{/* GENERATED by scripts/generate.py from the SDK registries — do not edit. */}"
)


# --- MDX helpers -----------------------------------------------------------


def mdx_escape(text: str) -> str:
    """Escape MDX-active characters ({, <) outside inline code spans."""
    parts = text.split("`")
    for i in range(0, len(parts), 2):
        parts[i] = parts[i].replace("{", "\\{").replace("<", "\\<")
    return "`".join(parts)


def cell(text: str) -> str:
    """Make text safe inside a markdown table cell."""
    return mdx_escape(text.replace("|", "\\|").replace("\n", " ").strip())


def frontmatter(title: str, description: str) -> str:
    return "---\ntitle: %s\ndescription: %s\n---\n\n%s\n" % (
        json.dumps(title),
        json.dumps(description),
        GENERATED_NOTE,
    )


def docs_markdown_url(docs_url: str) -> str:
    """Agent-fetchable markdown for a `/docs/...` page URL."""
    if docs_url == "/docs" or docs_url == "/docs/":
        return "/llms.mdx/docs/content.md"
    if not docs_url.startswith("/docs/"):
        raise ValueError(f"expected /docs/... path, got {docs_url!r}")
    return f"/llms.mdx{docs_url}/content.md"


def with_code_urls(path: str, url: str) -> dict[str, str]:
    """HTML viewer URL plus plain-text raw URL for the same file."""
    return {"url": url, "raw_url": f"/code/raw/{path}"}


def kebab(name: str) -> str:
    return name.replace("_", "-")


def body_after_summary(doc: str) -> str:
    """Docstring minus its first line — the page frontmatter already shows it."""
    _, _, rest = doc.partition("\n")
    return rest.strip()


# --- Parameter rendering ---------------------------------------------------


def schema_type(fragment: dict) -> str:
    """Human-readable type from a JSON-schema property fragment."""
    if "anyOf" in fragment:
        return "number \\| `\"all\"`"
    t = fragment.get("type", "any")
    if isinstance(t, list):
        return " \\| ".join(t)
    if t == "array":
        items = fragment.get("items", {}).get("type")
        return f"array of {items}" if items else "array"
    return t


def cli_flag(field_name: str) -> str:
    if field_name.endswith("_ss58"):
        base = field_name[: -len("_ss58")]
    else:
        base = field_name.replace("_ss58", "")
    return "--" + base.replace("_", "-")


def cli_placeholder(field_name: str, fragment: dict) -> str:
    if field_name.endswith("_ss58"):
        return "<ss58|name>"
    if "anyOf" in fragment:
        return "<amount|all>"
    t = fragment.get("type")
    if t == "integer":
        return "<int>"
    if t == "number":
        return "<number>"
    if t == "array":
        return "<a,b,c>"
    if t == "object":
        return "'<json>'"
    return "<value>"


def cli_arg(field_name: str, fragment: dict) -> str:
    """Full CLI arg for a field. Typer bools are ``--flag/--no-flag``."""
    if fragment.get("type") == "boolean":
        # Match the Typer bool pattern in cli (same as query --lite/--no-lite).
        flag = cli_flag(field_name)
        return f"{flag}/--no-{flag.removeprefix('--')}"
    return f"{cli_flag(field_name)} {cli_placeholder(field_name, fragment)}"


def py_placeholder(field_name: str, fragment: dict) -> str:
    if field_name == "netuid":
        return "1"
    if field_name in {"origin_netuid", "source_netuid"}:
        return "1"
    if field_name in {"dest_netuid", "destination_netuid"}:
        return "2"
    if field_name.endswith("_ss58"):
        if field_name.startswith(("dest_", "destination_", "new_")):
            return '"5G...destination"'
        if field_name.startswith(("origin_", "source_")):
            return '"5F...origin"'
        return '"5F..."'
    if "anyOf" in fragment:
        return "1.0"
    t = fragment.get("type")
    if t == "integer":
        return "0"
    if t == "number":
        return "1.0"
    if t == "boolean":
        return "True"
    if t == "array":
        return "[...]"
    if t == "object":
        return "{...}"
    return '"..."'


def params_table(schema: dict) -> str:
    props: dict = schema.get("properties", {})
    if not props:
        return "This operation takes no parameters.\n"
    required = set(schema.get("required", []))
    lines = [
        "| Parameter | Type | Required | Description |",
        "| --- | --- | --- | --- |",
    ]
    for name, fragment in props.items():
        lines.append(
            "| `%s` | %s | %s | %s |"
            % (
                name,
                schema_type(fragment),
                "yes" if name in required else "no",
                cell(fragment.get("description", "")),
            )
        )
    return "\n".join(lines) + "\n"


# --- On-chain implementation ------------------------------------------------
#
# Each intent declares the chain call(s) it wraps; the pages link (and quote)
# the actual dispatchable from the Rust source, served by the site's /code
# viewer. Extraction is deterministic over the checkout, so --check also
# catches docs whose line anchors drifted after a Rust change.

REPO_ROOT = APP_DIR.parents[2]

# Runtime pallet name (as used in Intent.wraps, storage containers, and the
# chain error catalog) -> in-repo crate directory.
PALLET_DIRS = {
    "SubtensorModule": "pallets/subtensor",
    "AdminUtils": "pallets/admin-utils",
    "Commitments": "pallets/commitments",
    "Crowdloan": "pallets/crowdloan",
    "Drand": "pallets/drand",
    "LimitOrders": "pallets/limit-orders",
    "MevShield": "pallets/shield",
    "Proxy": "pallets/proxy",
    "Swap": "pallets/swap",
    "Utility": "pallets/utility",
}

# Pallets referenced by intents, reads, or errors but implemented outside this
# repository's pallets/ tree — pages say so instead of linking.
UPSTREAM_PALLETS = {
    "Balances": "Substrate's `pallet_balances`",
    "Contracts": "Substrate's `pallet_contracts`",
    "Ethereum": "Frontier's `pallet_ethereum` (vendored under `vendor/frontier`)",
    "EVM": "Frontier's `pallet_evm` (vendored under `vendor/frontier`)",
    "Grandpa": "Substrate's `pallet_grandpa`",
    "Multisig": "Substrate's `pallet_multisig`",
    "Preimage": "Substrate's `pallet_preimage`",
    "SafeMode": "Substrate's `pallet_safe_mode`",
    "Scheduler": "Substrate's `pallet_scheduler`",
    "Sudo": "Substrate's `pallet_sudo`",
    "System": "Substrate's `frame_system`",
}

# Mirrors the /code corpus exclusions (src/lib/code.ts).
_EXCLUDED_RUST = {"tests.rs", "mock.rs", "benchmarks.rs", "benchmarking.rs"}


@functools.lru_cache(maxsize=None)
def pallet_sources(pallet_dir: str) -> tuple[tuple[str, list[str]], ...]:
    """(repo-relative path, lines) for each non-test source file of a crate."""
    out = []
    for path in sorted((REPO_ROOT / pallet_dir / "src").rglob("*.rs")):
        if "tests" in path.parts or path.name in _EXCLUDED_RUST:
            continue
        rel = str(path.relative_to(REPO_ROOT))
        out.append((rel, path.read_text().splitlines()))
    return tuple(out)


def brace_block_end(lines: list[str], start: int) -> int:
    """0-based index of the line closing the brace block opened at/after
    `start` (returns `start` when no block opens)."""
    depth = 0
    opened = False
    for k in range(start, len(lines)):
        depth += lines[k].count("{") - lines[k].count("}")
        opened = opened or "{" in lines[k]
        if opened and depth <= 0:
            return k
    return start


def find_dispatchable(pallet_dir: str, call: str) -> dict | None:
    """Locate `pub fn <call>` guarded by #[pallet::call_index]; return its
    file, 1-based line numbers, and the snippet from the attribute down to
    the closing brace."""
    fn_re = re.compile(rf"\s*pub fn {re.escape(call)}\s*\(")
    for rel, lines in pallet_sources(pallet_dir):
        for i, line in enumerate(lines):
            if not fn_re.match(line):
                continue
            # The attribute block above the fn; require call_index so plain
            # helpers with the same name never match. Intermediate lines may
            # be multi-line attributes (e.g. a weight tuple), so only another
            # function boundary invalidates the match.
            start = None
            for j in range(i - 1, max(0, i - 15) - 1, -1):
                if "#[pallet::call_index" in lines[j]:
                    start = j
                    break
                stripped = lines[j].strip()
                if "pub fn " in stripped or stripped == "}":
                    break
            if start is None:
                continue
            end = brace_block_end(lines, i)
            snippet = textwrap.dedent("\n".join(lines[start : end + 1]))
            return {
                "path": rel,
                "line": start + 1,
                "fn_line": i + 1,
                "end_line": end + 1,
                "body": lines[i : end + 1],
                "snippet": snippet,
            }
    return None


def find_fn(pallet_dir: str, name: str) -> tuple[str, int] | None:
    """First `pub fn <name>` in the crate (any impl block), as (path, line)."""
    fn_re = re.compile(rf"\s*pub(?:\(\w+\))? fn {re.escape(name)}\s*[(<]")
    for rel, lines in pallet_sources(pallet_dir):
        for i, line in enumerate(lines):
            if fn_re.match(line):
                return rel, i + 1
    return None


def range_anchor(found: dict) -> str:
    """#L<start>-L<end> covering the quoted snippet (attribute line through
    the closing brace) — the /code viewer highlights the whole range."""
    return f"#L{found['line']}-L{found['end_line']}"


@functools.lru_cache(maxsize=None)
def find_storage_item(pallet: str, name: str) -> tuple[str, int] | None:
    """Declaration of a #[pallet::storage] item, as (path, 1-based line of
    the `pub type` line). Only attribute/comment lines may sit between the
    storage attribute and the type alias."""
    pallet_dir = PALLET_DIRS.get(pallet)
    if pallet_dir is None:
        return None
    ty_re = re.compile(rf"\s*pub(?:\(\w+\))?\s+type\s+{re.escape(name)}\s*[<=]")
    for rel, lines in pallet_sources(pallet_dir):
        for i, line in enumerate(lines):
            if not ty_re.match(line):
                continue
            for j in range(i - 1, max(0, i - 12) - 1, -1):
                stripped = lines[j].strip()
                if stripped.startswith("#[pallet::storage"):
                    return rel, i + 1
                if not (
                    stripped.startswith("#[")
                    or stripped.startswith("//")
                    or stripped.endswith("]")
                    or stripped == ""
                ):
                    break
    return None


@functools.lru_cache(maxsize=None)
def find_error_variant(pallet: str, name: str) -> tuple[str, int] | None:
    """Declaration line of a #[pallet::error] enum variant, as (path, line)."""
    pallet_dir = PALLET_DIRS.get(pallet)
    if pallet_dir is None:
        return None
    var_re = re.compile(rf"\s*{re.escape(name)}\s*[,(=]")
    for rel, lines in pallet_sources(pallet_dir):
        for i, line in enumerate(lines):
            if "#[pallet::error]" not in line:
                continue
            k = i
            while k < len(lines) and "enum Error" not in lines[k]:
                k += 1
            if k == len(lines):
                continue
            end = brace_block_end(lines, k)
            for m in range(k + 1, end + 1):
                if var_re.match(lines[m]):
                    return rel, m + 1
    return None


# Crates searched for runtime-API implementations, in preference order: the
# rpc_info modules carry the real logic; runtime/src/lib.rs only has the
# impl_runtime_apis! glue and is the fallback.
_RUNTIME_API_DIRS = ("pallets/subtensor", "pallets/swap", "runtime")


@functools.lru_cache(maxsize=None)
def find_runtime_api_fn(method: str) -> dict | None:
    """Implementation of a runtime-API method, as {path, line, end_line} of
    the function body (searched across the rpc crates, then the runtime)."""
    fn_re = re.compile(rf"\s*(?:pub(?:\(\w+\))? )?fn {re.escape(method)}\s*[(<]")
    for pallet_dir in _RUNTIME_API_DIRS:
        for rel, lines in pallet_sources(pallet_dir):
            for i, line in enumerate(lines):
                if fn_re.match(line):
                    end = brace_block_end(lines, i)
                    return {"path": rel, "line": i + 1, "end_line": end + 1}
    return None


@functools.lru_cache(maxsize=None)
def find_runtime_constant(name: str) -> tuple[str, int] | None:
    """`pub const <name>` in the runtime's parameter_types, as (path, line)."""
    const_re = re.compile(rf"\s*pub const {re.escape(name)}\s*[:=]")
    for rel, lines in pallet_sources("runtime"):
        for i, line in enumerate(lines):
            if const_re.match(line):
                return rel, i + 1
    return None


# --- Read (query) chain targets ----------------------------------------------
#
# Reads reference their chain surface through the generated descriptor modules
# (`st.Pallet.Item`, `api.Api.method`, `constants.Pallet.Name`); scraping the
# fetch source for those references yields the storage items, runtime-API
# methods, and constants each read touches — resolved into /code links the
# same way tx pages resolve dispatchables.

_ST_REF_RE = re.compile(r"\bst\.(\w+)\.(\w+)")
_API_REF_RE = re.compile(r"\bapi\.(\w+)\.(\w+)")
_CONST_REF_RE = re.compile(r"\bconstants\.(\w+)\.(\w+)")


def _closure_targets(fetch) -> list[tuple[str, str, str]]:
    """(kind, container, name) for descriptor values captured in a fetch
    closure — how factory-made reads (scalar_read) carry their storage item."""
    kinds = {"storage": "storage", "runtime_apis": "runtime", "constants": "constant"}
    out = []
    for cell in fetch.__closure__ or ():
        value = cell.cell_contents
        module = type(value).__module__.rsplit(".", 1)[-1]
        if module in kinds and hasattr(value, "container") and hasattr(value, "name"):
            out.append((kinds[module], value.container, value.name))
    return out


def read_targets(spec) -> list[dict]:
    """Chain-side targets of a read, in first-use order, resolved into the
    /code corpus where possible. Each dict has kind/container/name and, when
    resolved, path/line(/end_line)/url."""
    try:
        src = inspect.getsource(spec.fetch)
    except (OSError, TypeError):
        src = ""
    scraped = []
    for kind, pattern in (
        ("storage", _ST_REF_RE),
        ("runtime", _API_REF_RE),
        ("constant", _CONST_REF_RE),
    ):
        scraped.extend((kind, container, name) for container, name in pattern.findall(src))
    out: list[dict] = []
    seen: set[tuple[str, str, str]] = set()
    for kind, container, name in [*scraped, *_closure_targets(spec.fetch)]:
        key = (kind, container, name)
        if key in seen:
            continue
        seen.add(key)
        target: dict = {"kind": kind, "container": container, "name": name}
        if kind == "storage":
            found = find_storage_item(container, name)
            if found:
                path, line = found
                target.update(
                    path=path,
                    line=line,
                    **with_code_urls(path, f"/code/{path}#L{line}"),
                )
        elif kind == "runtime":
            fn = find_runtime_api_fn(name)
            if fn:
                path = fn["path"]
                target.update(
                    path=path,
                    line=fn["line"],
                    end_line=fn["end_line"],
                    **with_code_urls(
                        path, f"/code/{path}#L{fn['line']}-L{fn['end_line']}"
                    ),
                )
        else:
            found = find_runtime_constant(name)
            if found:
                path, line = found
                target.update(
                    path=path,
                    line=line,
                    **with_code_urls(path, f"/code/{path}#L{line}"),
                )
        out.append(target)
    return out


def read_implementation_section(spec) -> str:
    """An "On-chain implementation" section listing the storage items,
    runtime-API methods, and constants a read touches, linked into /code.
    Reads served entirely by the client view layer get no section."""
    targets = read_targets(spec)
    if not targets:
        return ""
    kind_labels = {
        "storage": "Storage",
        "runtime": "Runtime API",
        "constant": "Constant",
    }
    lines = ["\n## On-chain implementation\n"]
    for t in targets:
        label = kind_labels[t["kind"]]
        full = f"{t['container']}.{t['name']}"
        if "url" in t:
            lines.append(f"- {label} [`{full}`]({t['url']})")
        elif t["container"] in UPSTREAM_PALLETS:
            lines.append(
                f"- {label} `{full}` — implemented by {UPSTREAM_PALLETS[t['container']]}, "
                "outside this repository's pallets."
            )
        else:
            lines.append(f"- {label} `{full}`")
    lines.append(
        "\nEvery file is browsable under [/code](/code) exactly as built into "
        "the runtime.\n"
    )
    return "\n".join(lines)


def delegate_links(pallet_dir: str, dispatchable: dict, call: str) -> list[str]:
    """Markdown links to the `Self::…` functions the dispatchable delegates
    to, in call order — the pointer past the thin wrapper into the logic."""
    links = []
    seen = set()
    for line in dispatchable["body"]:
        for name in re.findall(r"Self::(\w+)\s*\(", line):
            if name in seen or name == call:
                continue
            seen.add(name)
            found = find_fn(pallet_dir, name)
            if found:
                path, lineno = found
                links.append(f"[`{name}`](/code/{path}#L{lineno})")
    return links[:3]


def implementation_section(cls) -> str:
    if not cls.wraps:
        return ""
    parts = ["## On-chain implementation\n"]
    in_repo = [(p, c) for p, c in cls.wraps if p in PALLET_DIRS]

    # An intent fanning out over many calls (set_hyperparameter) gets a link
    # table; quoting dozens of near-identical dispatchables helps nobody.
    if len(in_repo) > 3:
        parts.append("| Chain call | Source |")
        parts.append("| --- | --- |")
        for pallet, call in in_repo:
            found = find_dispatchable(PALLET_DIRS[pallet], call)
            if found is None:
                raise RuntimeError(f"dispatchable {pallet}.{call} not found in Rust source")
            anchor = range_anchor(found)
            parts.append(
                f"| `{pallet}.{call}` | "
                f"[`{found['path']}#L{found['fn_line']}`](/code/{found['path']}{anchor}) |"
            )
        parts.append("")
    else:
        for pallet, call in cls.wraps:
            if pallet in UPSTREAM_PALLETS:
                parts.append(
                    f"`{pallet}.{call}` is implemented by {UPSTREAM_PALLETS[pallet]}, "
                    "outside this repository's pallets.\n"
                )
                continue
            found = find_dispatchable(PALLET_DIRS[pallet], call)
            if found is None:
                raise RuntimeError(f"dispatchable {pallet}.{call} not found in Rust source")
            anchor = range_anchor(found)
            parts.append(
                f"`{pallet}.{call}` — "
                f"[`{found['path']}#L{found['fn_line']}`](/code/{found['path']}{anchor}):\n"
            )
            parts.append(f"```rust\n{found['snippet']}\n```\n")
            links = delegate_links(PALLET_DIRS[pallet], found, call)
            if links:
                parts.append(f"Delegates to {', '.join(links)}.\n")

    parts.append(
        "Every file is browsable under [/code](/code) exactly as built into "
        "the runtime, or as plain text under `/code/raw/<path>` "
        "(index: [`/code/index.json`](/code/index.json)).\n"
    )
    return "\n" + "\n".join(parts)


# --- Intent (tx) pages -----------------------------------------------------

# `Intent.origin` classvar -> the human phrasing the docs show for it.
# "signed" is the extrinsic origin only — many calls still require a specific
# hotkey, beneficiary, or other pallet role (see each intent's body).
ORIGIN_LABELS = {
    "signed": "signed account (pallet role may apply)",
    "subnet_owner": "subnet owner",
    "root": "root (chain sudo)",
}


def intent_pallet(cls) -> str:
    return cls.wraps[0][0] if cls.wraps else "Other"


def verify_section(cls) -> str:
    """A "Verify" section linking to the read that confirms the intent's
    effect (``cls.verify``), when the intent declares one."""
    if not cls.verify:
        return ""
    name = kebab(cls.verify)
    spec = READS.get(cls.verify)
    if spec is not None:
        cli_parts, _ = read_cli_invocation(spec)
        cmd = " ".join(cli_parts) + " --json"
    else:
        cmd = f"btcli query {name} --json"
    return f"""
## Verify

After inclusion, confirm the effect with the
[`{name}`](/docs/query/{name}) read:

```bash
{cmd}
```
"""


def wrap_link(pallet: str, call: str) -> str:
    """`Pallet.call` linked to its dispatchable in /code when in-repo."""
    if pallet in PALLET_DIRS:
        found = find_dispatchable(PALLET_DIRS[pallet], call)
        if found:
            return f"[`{pallet}.{call}`](/code/{found['path']}{range_anchor(found)})"
    return f"`{pallet}.{call}`"


def intent_page(op: str, cls) -> str:
    description = cls.describe()
    summary = description.split("\n")[0]
    schema = cls.json_schema()
    props = schema.get("properties", {})
    required = [n for n in schema.get("required", []) if n in props]

    wraps = ", ".join(wrap_link(p, c) for p, c in cls.wraps) or "—"
    body = mdx_escape(body_after_summary(description))

    # Intents may pin a friendlier CLI spelling (e.g. root registration goes
    # through the ordinary `subnets register` command); default to the
    # generic tx command.
    cli_parts = [getattr(cls, "cli_example", None) or f"btcli tx {kebab(op)}"]
    for name in required:
        cli_parts.append(cli_arg(name, props[name]))
    cli_cmd = " \\\n  ".join(cli_parts)

    examples = {
        "trim_subnet": {"max_n": "64"},
        "trim_null_subnet_batch": {"target": "64"},
    }.get(op, {})
    py_args = ", ".join(
        f"{n}={examples.get(n, py_placeholder(n, props[n]))}" for n in required
    )
    class_name = cls.__name__

    return f"""{frontmatter(kebab(op), summary)}
{body}

| Signer | Origin | Pallet | Wraps |
| --- | --- | --- | --- |
| `{cls.signer}` | {ORIGIN_LABELS[cls.origin]} | {intent_pallet(cls)} | {wraps} |
{verify_section(cls)}
## Parameters

{params_table(schema)}
Address parameters (`--hotkey`, `--coldkey`, `--dest`, ...) accept a raw ss58
address, an address-book or proxy-book name, or a local wallet/hotkey name.

## CLI

Preview with `--dry-run` (shows fee, effects, and policy result without
submitting), then submit:

```bash
{cli_cmd} --dry-run
{cli_cmd} -w my_coldkey
```

## Python

```python
import bittensor as bt
from bittensor.wallet import Wallet

wallet = Wallet(name="my_coldkey", hotkey="my_hotkey")
intent = bt.{class_name}({py_args})

sub = bt.Subtensor()
plan = sub.plan(intent, wallet)   # fee, effects, policy — no submission
result = sub.execute(intent, wallet)
if not result.success:
    print(result.error.code, result.error.remediation)
```

(`bt.Subtensor` is also the async client — `async with bt.Subtensor() as client:`
— see [The client](/docs/concepts/client).) Or build the intent by op name, as
an agent would:

```python
result = sub.execute_tool("{op}", {{...}}, wallet)
```
{implementation_section(cls)}"""


def intent_index() -> str:
    header = frontmatter(
        "Transactions",
        "Every state-changing operation: one page per intent, generated from the SDK.",
    )
    groups: dict[str, list[tuple[str, type]]] = {}
    for op, cls in sorted(INTENTS.items()):
        groups.setdefault(intent_pallet(cls), []).append((op, cls))

    parts = [
        header,
        "Every mutation is an **intent**: preview it with `plan` / `--dry-run`, "
        "submit it with `execute`. Each CLI command below is `btcli tx <name>`; "
        "each Python class is `bt.<ClassName>`. The machine-readable catalog of all "
        "of these (with JSON schemas) is at [`/catalog/intents.json`](/catalog/intents.json) "
        "or via `btcli tools` / `bt.intents.list_tools()`.\n",
    ]
    for pallet in sorted(groups):
        parts.append(f"## {pallet}\n")
        parts.append("| Operation | Signer | Origin | Summary |")
        parts.append("| --- | --- | --- | --- |")
        for op, cls in groups[pallet]:
            summary = cls.describe().split("\n")[0]
            parts.append(
                f"| [`{kebab(op)}`](/docs/tx/{kebab(op)}) | {cls.signer} | "
                f"{ORIGIN_LABELS[cls.origin]} | {cell(summary)} |"
            )
        parts.append("")
    return "\n".join(parts)


def tx_meta() -> dict:
    groups: dict[str, list[str]] = {}
    for op, cls in sorted(INTENTS.items()):
        groups.setdefault(intent_pallet(cls), []).append(kebab(op))
    pages: list[str] = ["index"]
    for pallet in sorted(groups):
        pages.append(f"---{pallet}---")
        pages.extend(groups[pallet])
    return {"title": "Transactions", "pages": pages}


# --- Read (query) pages ----------------------------------------------------

_JSON_PY_PLACEHOLDER = {
    "integer": "1",
    "number": "1.0",
    "boolean": "True",
    "string": '"..."',
    "array": "[...]",
}


def namespace_attr(spec) -> str:
    return NAMESPACE_ATTR[spec.category]


def namespace_shadowed(spec) -> bool:
    """Whether a curated method with *different semantics* hides this read on
    its namespace (e.g. ``subnets.metagraph`` returns the typed Metagraph, not
    this read's raw record) — such reads stay name-dispatch only in the docs.
    Detected by a differing return annotation; a curated method that merely
    wraps the read (same name, same return type) documents fine either way."""
    cls = NAMESPACES[namespace_attr(spec)]
    curated = vars(cls).get(spec.name)
    if curated is None:
        return False
    curated_returns = inspect.signature(curated).return_annotation
    read_returns = inspect.signature(spec.fetch).return_annotation
    return curated_returns != read_returns


def namespace_call(spec, py_kwargs: list[str]) -> str:
    return f"sub.{namespace_attr(spec)}.{spec.name}({', '.join(py_kwargs)})"


def read_cli_invocation(spec) -> tuple[list[str], list[str]]:
    """The ``btcli query`` command parts and Python kwarg placeholders for a read."""
    cli_parts = [f"btcli query {kebab(spec.name)}"]
    py_kwargs = []
    for name, jtype in spec.params.items():
        # Match cli/query.py: any param with `_ss58` (singular or plural
        # `*_ss58s`) uses address_cli_name / cli_flag, not raw kebab.
        if "_ss58" in name:
            placeholder = "<array>" if jtype == "array" else "<ss58|name>"
            cli_parts.append(f"{cli_flag(name)} {placeholder}")
            py_value = "[...]" if jtype == "array" else '"5F..."'
        elif jtype == "boolean":
            # Match the Typer bool pattern in cli/query.py (--flag/--no-flag).
            flag = f"--{kebab(name)}"
            cli_parts.append(f"{flag}/--no-{kebab(name)}")
            py_value = _JSON_PY_PLACEHOLDER.get(jtype, "...")
        else:
            cli_parts.append(f"--{kebab(name)} <{jtype}>")
            py_value = _JSON_PY_PLACEHOLDER.get(jtype, "...")
        py_kwargs.append(f"{name}={py_value}")
    return cli_parts, py_kwargs


def read_page(spec) -> str:
    body = mdx_escape(body_after_summary(spec.doc))
    if spec.params:
        lines = [
            "| Parameter | Type | Description |",
            "| --- | --- | --- |",
        ]
        for name, jtype in spec.params.items():
            lines.append(
                f"| `{name}` | {jtype} | {cell(spec.param_docs.get(name, ''))} |"
            )
        table = "\n".join(lines) + "\n"
    else:
        table = "This read takes no parameters.\n"

    cli_parts, py_kwargs = read_cli_invocation(spec)

    read_call = f"sub.read({', '.join([json.dumps(spec.name), *py_kwargs])})"
    if namespace_shadowed(spec):
        # A curated method with different semantics owns this name on the
        # namespace, so the page documents the name-dispatch form only.
        python_section = f"""```python
import bittensor as bt

sub = bt.Subtensor()
result = {read_call}
```"""
    else:
        python_section = f"""Namespace method (autocomplete, signature help):

```python
import bittensor as bt

sub = bt.Subtensor()
result = {namespace_call(spec, py_kwargs)}
```

Or dispatch by name, as an agent would:

```python
result = {read_call}
```

Async is the same surface awaited: `async with bt.Subtensor() as client:`."""

    return f"""{frontmatter(kebab(spec.name), spec.summary)}
{body}

**Category:** {spec.category}

## Parameters

{table}
## CLI

```bash
{" ".join(cli_parts)} --json
```

## Python

{python_section}
{read_implementation_section(spec)}"""


def read_index() -> str:
    header = frontmatter(
        "Queries",
        "Every chain read: one page per query, generated from the SDK.",
    )
    groups: dict[str, list] = {}
    for spec in sorted(READS.values(), key=lambda s: s.name):
        groups.setdefault(spec.category, []).append(spec)

    parts = [
        header,
        "Reads are free, unsigned, and safe to call at any time. Each CLI command "
        "is `btcli query <name>` (add `--json` for machine-readable output). In "
        "Python every read is a typed method on its category's namespace — "
        "`sub.subnets.subnet_registration_cost()`, "
        "`sub.delegation.delegates()` on `sub = bt.Subtensor()` (awaited on the "
        "async client) — with autocomplete and signature "
        "help; `sub.read(\"<name>\", ...)` dispatches the same read by "
        "name. The machine-readable catalog is at "
        "[`/catalog/reads.json`](/catalog/reads.json) or via "
        "`bt.reads.list_reads()`.\n",
    ]
    for category in sorted(groups):
        parts.append(f"## {category}\n")
        parts.append("| Query | Summary |")
        parts.append("| --- | --- |")
        for spec in groups[category]:
            parts.append(
                f"| [`{kebab(spec.name)}`](/docs/query/{kebab(spec.name)}) | {cell(spec.summary)} |"
            )
        parts.append("")
    return "\n".join(parts)


def query_meta() -> dict:
    groups: dict[str, list[str]] = {}
    for spec in sorted(READS.values(), key=lambda s: s.name):
        groups.setdefault(spec.category, []).append(kebab(spec.name))
    pages: list[str] = ["index"]
    for category in sorted(groups):
        pages.append(f"---{category}---")
        pages.extend(groups[category])
    return {"title": "Queries", "pages": pages}


# --- Error pages -----------------------------------------------------------


def sentence_case(text: str) -> str:
    """Capitalize the first letter of each paragraph.

    The SDK's remediation strings are terminal-style lowercase; on a web page
    that reads as a typo rather than a style.
    """
    paragraphs = []
    for paragraph in text.split("\n\n"):
        stripped = paragraph.lstrip()
        prefix = paragraph[: len(paragraph) - len(stripped)]
        paragraphs.append(prefix + stripped[:1].upper() + stripped[1:])
    return "\n\n".join(paragraphs)


def chain_errors_for(code) -> list[str]:
    """Chain error names classifying to a code, sorted."""
    return sorted(n for n, c in error_map.NAME_TO_CODE.items() if c is code)


# Chain error name -> the pallets that declare it (a name can exist in several).
CHAIN_ERROR_PALLETS: dict[str, list[str]] = {}
for _info in CHAIN_ERROR_CATALOG.values():
    _pallets = CHAIN_ERROR_PALLETS.setdefault(_info.name, [])
    if _info.pallet not in _pallets:
        _pallets.append(_info.pallet)


def chain_error_remediation(name: str) -> str:
    """The remediation the CLI would print for this exact chain error (includes
    the per-name overrides, e.g. SlippageTooHigh's tolerance flags)."""
    return result.ChainError("", name=name).remediation


def error_page(code) -> str:
    """One explainer page per semantic error code (the hyperparameters layout:
    an index table linking to a page per entry). The page carries the long-form
    explanation (`btcli explain <code>`), the remediation hint, and the chain
    errors that classify to this code."""
    remediation = sentence_case(result.REMEDIATION[code])
    explanation = sentence_case(result.EXPLANATIONS[code])
    header = frontmatter(code.value, remediation)
    parts = [header, mdx_escape(explanation) + "\n"]

    parts.append("## Remediation\n")
    parts.append(mdx_escape(remediation) + "\n")

    names = chain_errors_for(code)
    parts.append("## Chain errors\n")
    if names:
        parts.append(
            f"The exact chain error names (from the extrinsic receipt) that "
            f"classify to `{code.value}`; the description says what triggered "
            "the failure and where to check. Each name has its own page:\n"
        )
        parts.append("| Chain error | Description |")
        parts.append("| --- | --- |")
        for name in names:
            description = error_descriptions.DESCRIPTIONS[name]
            parts.append(f"| [`{name}`](/docs/errors/chain/{name}) | {cell(description)} |")
        parts.append("")
    else:
        parts.append(
            "No chain error classifies to this code — it is raised client-side "
            "by the SDK before or after the call reaches the chain.\n"
        )
    parts.append(
        "The same explanation is available in the terminal: "
        f"`btcli explain {code.value}` (or `btcli explain <ChainErrorName>` "
        "for one exact chain error).\n"
    )
    return "\n".join(parts)


def errors_index() -> str:
    header = frontmatter(
        "Errors",
        "Every failure carries a machine-readable code and a remediation hint.",
    )
    parts = [
        header,
        "A failed `execute` returns an `ExtrinsicResult` whose `error` has a "
        "semantic `code` (branch on it) and a `remediation` hint (what to try "
        "next). Every chain error name is deliberately classified — a CI gate "
        "keeps the mapping complete in both directions. Each code has its own "
        "explainer page listing the chain errors that map to it, and every "
        "exact chain error name has its own page under "
        "[chain errors](/docs/errors/chain). The machine-readable version is "
        "at [`/catalog/errors.json`](/catalog/errors.json).\n",
        "| Code | Chain errors | Remediation |",
        "| --- | --- | --- |",
    ]
    for code in error_map.ErrorCode:
        remediation = sentence_case(result.REMEDIATION[code])
        count = len(chain_errors_for(code))
        parts.append(
            f"| [`{code.value}`](/docs/errors/{kebab(code.value)}) | "
            f"{count if count else '—'} | {cell(remediation)} |"
        )
    parts.append("")
    return "\n".join(parts)


def errors_meta() -> dict:
    return {
        "title": "Errors",
        "pages": [
            "index",
            *(kebab(code.value) for code in error_map.ErrorCode),
            "chain",
        ],
    }


def chain_error_page(name: str, code) -> str:
    """One page per exact chain error name, at /docs/errors/chain/<Name> (the
    URL keeps the on-chain CamelCase name so CLI links never need mangling)."""
    description = sentence_case(error_descriptions.DESCRIPTIONS[name])
    remediation = sentence_case(chain_error_remediation(name))
    pallets = CHAIN_ERROR_PALLETS.get(name, [])
    header = frontmatter(name, remediation)
    parts = [header, mdx_escape(description) + "\n"]

    pallet_list = ", ".join(f"`{p}`" for p in pallets)
    origin = (
        f"Declared by the {pallet_list} pallet{'s' if len(pallets) > 1 else ''}; it"
        if pallets
        else "It"
    )
    parts.append(
        f"{origin} classifies to the semantic code "
        f"[`{code.value}`](/docs/errors/{kebab(code.value)}).\n"
    )

    # The declaration site(s) in the chain source, for in-repo pallets.
    sources = []
    for pallet in pallets:
        found = find_error_variant(pallet, name)
        if found:
            path, line = found
            sources.append(f"[`{path}#L{line}`](/code/{path}#L{line})")
    if sources:
        parts.append(f"Declared at {', '.join(sources)}.\n")

    parts.append("## Remediation\n")
    parts.append(mdx_escape(remediation) + "\n")

    parts.append(
        "The same explanation is available in the terminal: "
        f"`btcli explain {name}`.\n"
    )
    return "\n".join(parts)


def chain_errors_index() -> str:
    header = frontmatter(
        "Chain errors",
        "Every exact chain error name, classified to a semantic code.",
    )
    parts = [
        header,
        "The exact chain error name (from the extrinsic receipt) maps to a "
        "semantic [code](/docs/errors); the description says what triggered "
        "the failure and where to check. Each name has its own page:\n",
        "| Chain error | Code | Description |",
        "| --- | --- | --- |",
    ]
    for name, code in sorted(error_map.NAME_TO_CODE.items()):
        description = error_descriptions.DESCRIPTIONS[name]
        parts.append(
            f"| [`{name}`](/docs/errors/chain/{name}) | "
            f"[`{code.value}`](/docs/errors/{kebab(code.value)}) | "
            f"{cell(description)} |"
        )
    parts.append("")
    return "\n".join(parts)


def chain_errors_meta() -> dict:
    return {
        "title": "Chain errors",
        "pages": ["index", *sorted(error_map.NAME_TO_CODE)],
    }


# --- Hyperparameters page ---------------------------------------------------

# Unit kind -> the label the docs table shows for it.
UNIT_LABELS = {
    "u16": "fraction (u16, 65535 = 1.0)",
    "u64": "fraction (u64, u64::MAX = 1.0)",
    "per_million": "fraction (1,000,000 = 1.0)",
    "rao": "TAO amount in rao",
    "blocks": "blocks (12s)",
    "epochs": "epochs (tempos)",
    "difficulty": "PoW difficulty (u64)",
    "fixed128": "multiplier (U64F64 bits / 2^64)",
    "int": "integer",
    "bool": "flag",
}


def hyperparameters_index() -> str:
    """The overview table; each parameter links to its hand-written explainer
    page (docs/hyperparameters/<kebab>.mdx, checked for existence by --check)."""
    header = frontmatter(
        "Hyperparameters",
        "What each subnet hyperparameter controls, its unit, and how to change it.",
    )
    parts = [
        header,
        "Read them with `btcli sudo get --netuid N` (the "
        "[`subnet_hyperparameters`](/docs/query/subnet-hyperparameters) read); the "
        "subnet owner changes the owner-settable ones with `btcli sudo set` (the "
        "[`set_hyperparameter`](/docs/tx/set-hyperparameter) intent). Raw on-chain "
        "integers are primary; where a parameter is a fixed-point fraction or a rao "
        "amount, the value also accepts the human form with a decimal point. "
        "Each parameter has its own explainer page; the source column links "
        "the on-chain storage declaration.\n",
        "| Hyperparameter | Unit | Owner-settable | What it controls | Source |",
        "| --- | --- | --- | --- | --- |",
    ]
    for name, meta in hyperparams.HYPERPARAMS.items():
        settable = "yes" if name in OWNER_HYPERPARAMETERS else "root only"
        unit = UNIT_LABELS[hyperparams.kind_of(name)]
        source = "—"
        item = hyperparams.STORAGE_ITEMS.get(name)
        if item is not None:
            found = find_storage_item(item.container, item.name)
            if found:
                path, line = found
                source = f"[`{item.name}`](/code/{path}#L{line})"
        parts.append(
            f"| [`{name}`](/docs/hyperparameters/{kebab(name)}) | {unit} | "
            f"{settable} | {cell(meta.short)} | {source} |"
        )
    parts.append("")
    return "\n".join(parts)


def hyperparameters_meta() -> dict:
    return {
        "title": "Hyperparameters",
        "pages": ["index", *(kebab(name) for name in hyperparams.HYPERPARAMS)],
    }


# --- Catalogs --------------------------------------------------------------


def intent_examples(op: str, cls) -> dict:
    schema = cls.json_schema()
    props = schema.get("properties", {})
    required = [n for n in schema.get("required", []) if n in props]
    cli = f"btcli tx {kebab(op)} " + " ".join(
        cli_arg(n, props[n]) for n in required
    )
    return {"cli": cli.strip(), "python_class": cls.__name__}


def intent_sources(cls) -> list[dict]:
    """Resolved /code locations for the dispatchables an intent wraps."""
    sources = []
    for pallet, call in cls.wraps:
        if pallet not in PALLET_DIRS:
            continue
        found = find_dispatchable(PALLET_DIRS[pallet], call)
        if found is None:
            continue
        path = found["path"]
        sources.append(
            {
                "pallet": pallet,
                "call": call,
                "path": path,
                "line": found["fn_line"],
                "end_line": found["end_line"],
                **with_code_urls(path, f"/code/{path}{range_anchor(found)}"),
            }
        )
    return sources


def chain_error_sources(name: str) -> list[dict]:
    """Resolved /code declaration sites for a chain error name."""
    sources = []
    for pallet in CHAIN_ERROR_PALLETS.get(name, []):
        found = find_error_variant(pallet, name)
        if found is None:
            continue
        path, line = found
        sources.append(
            {
                "pallet": pallet,
                "path": path,
                "line": line,
                **with_code_urls(path, f"/code/{path}#L{line}"),
            }
        )
    return sources


def write_catalogs(catalog_root: Path) -> None:
    catalog_root.mkdir(parents=True, exist_ok=True)
    tools = list_tools()
    by_op = {t["name"]: t for t in tools}
    for op, cls in INTENTS.items():
        by_op[op].update(intent_examples(op, cls))
        docs_url = f"/docs/tx/{kebab(op)}"
        by_op[op]["docs_url"] = docs_url
        by_op[op]["markdown_url"] = docs_markdown_url(docs_url)
        by_op[op]["wraps"] = [list(pair) for pair in cls.wraps]
        sources = intent_sources(cls)
        if sources:
            by_op[op]["sources"] = sources
    reads = list_reads()
    for r in reads:
        docs_url = f"/docs/query/{kebab(r['name'])}"
        r["docs_url"] = docs_url
        r["markdown_url"] = docs_markdown_url(docs_url)
        spec = READS[r["name"]]
        if not namespace_shadowed(spec):
            r["python"] = f"sub.{namespace_attr(spec)}.{spec.name}(...)"
        hits = read_targets(spec)
        if hits:
            r["hits"] = hits
    codes = {}
    for code in error_map.ErrorCode:
        docs_url = f"/docs/errors/{kebab(code.value)}"
        codes[code.value] = {
            "remediation": result.REMEDIATION[code],
            "docs_url": docs_url,
            "markdown_url": docs_markdown_url(docs_url),
        }
    chain_errors = {}
    for n, c in sorted(error_map.NAME_TO_CODE.items()):
        docs_url = f"/docs/errors/chain/{n}"
        entry = {
            "code": c.value,
            "description": error_descriptions.DESCRIPTIONS[n],
            "docs_url": docs_url,
            "markdown_url": docs_markdown_url(docs_url),
            "pallets": CHAIN_ERROR_PALLETS.get(n, []),
        }
        sources = chain_error_sources(n)
        if sources:
            entry["sources"] = sources
        chain_errors[n] = entry
    errors = {
        "note": (
            "Semantic ErrorCode values are under `codes` (snake_case keys). "
            "Exact on-chain error names are under `chain_errors` (CamelCase keys). "
            "Each entry has `docs_url` (HTML page) and `markdown_url` (raw markdown)."
        ),
        "codes": codes,
        "chain_errors": chain_errors,
    }
    (catalog_root / "intents.json").write_text(json.dumps(tools, indent=2) + "\n")
    (catalog_root / "reads.json").write_text(json.dumps(reads, indent=2) + "\n")
    (catalog_root / "errors.json").write_text(json.dumps(errors, indent=2) + "\n")


# --- Driver ----------------------------------------------------------------


def generate(content_root: Path) -> None:
    # Emit into a temp dir first, then swap in the results, so an exception
    # mid-emit cannot leave the committed tree half-deleted.
    content_root.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(dir=content_root) as tmp:
        tx_dir = Path(tmp) / "tx"
        query_dir = Path(tmp) / "query"
        errors_dir = Path(tmp) / "errors"
        tx_dir.mkdir()
        query_dir.mkdir()
        errors_dir.mkdir()

        for op, cls in sorted(INTENTS.items()):
            (tx_dir / f"{kebab(op)}.mdx").write_text(intent_page(op, cls))
        (tx_dir / "index.mdx").write_text(intent_index())
        (tx_dir / "meta.json").write_text(json.dumps(tx_meta(), indent=2) + "\n")

        for spec in sorted(READS.values(), key=lambda s: s.name):
            (query_dir / f"{kebab(spec.name)}.mdx").write_text(read_page(spec))
        (query_dir / "index.mdx").write_text(read_index())
        (query_dir / "meta.json").write_text(json.dumps(query_meta(), indent=2) + "\n")

        for code in error_map.ErrorCode:
            (errors_dir / f"{kebab(code.value)}.mdx").write_text(error_page(code))
        (errors_dir / "index.mdx").write_text(errors_index())
        (errors_dir / "meta.json").write_text(json.dumps(errors_meta(), indent=2) + "\n")

        chain_dir = errors_dir / "chain"
        chain_dir.mkdir()
        for name, code in sorted(error_map.NAME_TO_CODE.items()):
            (chain_dir / f"{name}.mdx").write_text(chain_error_page(name, code))
        (chain_dir / "index.mdx").write_text(chain_errors_index())
        (chain_dir / "meta.json").write_text(json.dumps(chain_errors_meta(), indent=2) + "\n")

        for src, dest in (
            (tx_dir, content_root / "tx"),
            (query_dir, content_root / "query"),
            (errors_dir, content_root / "errors"),
        ):
            if dest.exists():
                shutil.rmtree(dest)
            src.rename(dest)
        # The errors section used to be a single generated errors.mdx page;
        # drop the leftover so it does not shadow the errors/ folder.
        (content_root / "errors.mdx").unlink(missing_ok=True)
        # Only the index and meta are generated: the per-parameter explainer
        # pages in this folder are hand-written and left untouched.
        hyperparams_dir = content_root / "hyperparameters"
        hyperparams_dir.mkdir(exist_ok=True)
        (hyperparams_dir / "index.mdx").write_text(hyperparameters_index())
        (hyperparams_dir / "meta.json").write_text(
            json.dumps(hyperparameters_meta(), indent=2) + "\n"
        )


def check() -> int:
    """Regenerate into a temp dir and diff against the committed output."""
    stale: list[str] = []
    with tempfile.TemporaryDirectory() as tmp:
        tmp_content = Path(tmp) / "content"
        tmp_catalog = Path(tmp) / "catalog"
        tmp_content.mkdir()
        generate(tmp_content)
        write_catalogs(tmp_catalog)
        for fresh_root, committed_root in (
            (tmp_content, CONTENT),
            (tmp_catalog, CATALOG),
        ):
            for fresh in sorted(fresh_root.rglob("*")):
                if fresh.is_dir():
                    continue
                rel = fresh.relative_to(fresh_root)
                committed = committed_root / rel
                if not committed.exists() or not filecmp.cmp(fresh, committed, shallow=False):
                    stale.append(str(committed))
        # Files that were generated once but no longer are (e.g. a removed intent).
        for sub in ("tx", "query", "errors"):
            committed_dir = CONTENT / sub
            if not committed_dir.exists():
                continue
            for committed in sorted(committed_dir.rglob("*")):
                if committed.is_file() and not (tmp_content / committed.relative_to(CONTENT)).exists():
                    stale.append(str(committed))
        # The pre-folder single errors page must not linger beside errors/.
        if (CONTENT / "errors.mdx").exists():
            stale.append(str(CONTENT / "errors.mdx"))
        # Every hyperparameter must have its hand-written explainer page.
        for name in hyperparams.HYPERPARAMS:
            page = CONTENT / "hyperparameters" / f"{kebab(name)}.mdx"
            if not page.exists():
                stale.append(f"{page} (missing explainer page)")
    if stale:
        print("Generated docs are stale; run scripts/generate.py:", file=sys.stderr)
        for path in stale:
            print(f"  {path}", file=sys.stderr)
        return 1
    print("Generated docs are up to date.")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify committed output is fresh")
    args = parser.parse_args()
    if args.check:
        return check()
    generate(CONTENT)
    write_catalogs(CATALOG)
    n_tx, n_q = len(INTENTS), len(READS)
    n_err = len(list(error_map.ErrorCode))
    n_chain = len(error_map.NAME_TO_CODE)
    print(
        f"Generated {n_tx} tx pages, {n_q} query pages, {n_err} error pages, "
        f"{n_chain} chain error pages, the hyperparameters index, and 3 catalogs."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
