[package]
name = "subtensor-swap-interface"
version = "0.1.0"
edition.workspace = true

[dependencies]
codec = { workspace = true, features = ["derive"] }
frame-support.workspace = true
scale-info.workspace = true
substrate-fixed.workspace = true
subtensor-runtime-common.workspace = true

[lints]
workspace = true

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-support/std",
	"scale-info/std",
	"substrate-fixed/std",
	"subtensor-runtime-common/std",
]
