[package]
name = "subtensor-swap-interface"
version = "0.1.0"
edition.workspace = true

[package.metadata.cargo-machete]
ignored = [
    "codec",                   # Used in serialization features
    "scale-info"               # Used in metadata features
]

[dependencies]
codec = { workspace = true, features = ["derive"] }
frame-support.workspace = true
scale-info = { workspace = true, features = ["derive"] }
substrate-fixed.workspace = true
subtensor-runtime-common.workspace = true

[lints]
workspace = true

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-support/std",
	"scale-info/std",
	"substrate-fixed/std",
	"subtensor-runtime-common/std",
]
