[package]
name = "subtensor-tools"
version = "0.1.0"
edition.workspace = true
license = "MIT"

description = "support tools for Subtensor"
repository = "https://github.com/opentensor/subtensor"
homepage = "https://bittensor.com"

[[bin]]
name = "bump-version"
path = "src/bump_version.rs"

[[bin]]
name = "spec-version"
path = "src/spec_version.rs"

[dependencies]
anyhow.workspace = true
clap = { workspace = true, features = ["derive"] }
semver.workspace = true
toml_edit.workspace = true
node-subtensor-runtime = { workspace = true, default-features = true }
