[package]
name = "pallet-subtensor"
version = "4.0.0-dev"
description = "FRAME pallet for runtime logic of Subtensor Blockchain."
authors = ["Bittensor Nucleus Team"]
homepage = "https://bittensor.com"
edition = "2024"
license = "Unlicense"
publish = false
repository = "https://github.com/opentensor/subtensor"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
subtensor-macros.workspace = true
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = [
	"derive",
] }
sp-core = { workspace = true }
pallet-balances = { workspace = true }
scale-info = { workspace = true, features = ["derive"] }
frame-benchmarking = { workspace = true, optional = true }
frame-support = { workspace = true }
frame-system = { workspace = true }
sp-io = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde-tuple-vec-map = { workspace = true }
serde_bytes = { workspace = true, features = ["alloc"] }
serde_with = { workspace = true, features = ["macros"] }
sp-runtime = { workspace = true }
sp-std = { workspace = true }
libsecp256k1 = { workspace = true }
log = { workspace = true }
substrate-fixed = { workspace = true }
pallet-transaction-payment = { workspace = true }
pallet-utility-opentensor = { workspace = true }
ndarray = { workspace = true }
hex = { workspace = true }
share-pool = { default-features = false, path = "../../primitives/share-pool" }
safe-math = { default-features = false, path = "../../primitives/safe-math" }
approx = { workspace = true }
subtensor-swap-interface = { workspace = true }
subtensor-runtime-common = { workspace = true, features = ["approx"] }

pallet-collective = { version = "4.0.0-dev", default-features = false, path = "../collective" }
pallet-drand = { path = "../drand", default-features = false }
pallet-babe = { workspace = true }
pallet-aura = { workspace = true }
pallet-timestamp = { workspace = true }
pallet-evm = { workspace = true }
pallet-membership = { workspace = true }
hex-literal = { workspace = true }
num-traits = { version = "0.2.19", default-features = false, features = [
	"libm",
] }
tle = { workspace = true, default-features = false }
ark-bls12-381 = { workspace = true, default-features = false }
ark-serialize = { workspace = true, default-features = false }
w3f-bls = { workspace = true, default-features = false }
sha2 = { workspace = true }
array-bytes = { workspace = true }
rand_chacha = { workspace = true }
runtime-common = { workspace = true }
sp-consensus-babe = { workspace = true }
sp-consensus-aura = { workspace = true }
sp-consensus-slots = { workspace = true }
pallet-crowdloan = { workspace = true, default-features = false }
pallet-proxy-opentensor = { workspace = true, default-features = false }

[dev-dependencies]
pallet-balances = { workspace = true, features = ["std"] }
pallet-scheduler = { workspace = true }
pallet-subtensor-swap = { workspace = true }
sp-version = { workspace = true }
# Substrate
sp-tracing = { workspace = true }
parity-util-mem = { workspace = true, features = ["primitive-types"] }
rand = { workspace = true }
sp-core = { workspace = true }
sp-std = { workspace = true }
pallet-preimage = { workspace = true }

[features]
std = [
	"ark-bls12-381/std",
	"ark-serialize/std",
	"codec/std",
	"frame-benchmarking/std",
	"frame-support/std",
	"frame-system/std",
	"hex/std",
	"libsecp256k1/std",
	"log/std",
	"ndarray/std",
	"num-traits/std",
	"pallet-balances/std",
	"pallet-collective/std",
	"pallet-drand/std",
	"pallet-evm/std",
	"pallet-membership/std",
	"pallet-preimage/std",
	"pallet-scheduler/std",
	"pallet-subtensor-swap/std",
	"pallet-transaction-payment/std",
	"rand_chacha/std",
	"safe-math/std",
	"scale-info/std",
	"serde/std",
	"serde_bytes/std",
	"serde_json/std",
	"serde_with/std",
	"sha2/std",
	"share-pool/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
	"sp-tracing/std",
	"sp-version/std",
	"substrate-fixed/std",
	"substrate-fixed/std",
	"subtensor-runtime-common/std",
	"subtensor-swap-interface/std",
	"tle/std",
	"w3f-bls/std",
	"runtime-common/std",
	"pallet-aura/std",
	"pallet-babe/std",
	"sp-consensus-babe/std",
	"sp-consensus-aura/std",
	"pallet-timestamp/std",
	"sp-consensus-slots/std",
	"rand_chacha/std",
	"safe-math/std",
	"sha2/std",
	"share-pool/std",
	"subtensor-runtime-common/std",
	"pallet-crowdloan/std",
	"pallet-proxy-opentensor/std",
	"pallet-utility-opentensor/std"
]
default = ["std"]
runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-membership/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"pallet-collective/runtime-benchmarks",
	"pallet-evm/runtime-benchmarks",
	"pallet-drand/runtime-benchmarks",
	"pallet-membership/runtime-benchmarks",
	"pallet-preimage/runtime-benchmarks",
	"pallet-scheduler/runtime-benchmarks",
	"pallet-drand/runtime-benchmarks",
	"runtime-common/runtime-benchmarks",
	"pallet-babe/runtime-benchmarks",
	"pallet-timestamp/runtime-benchmarks",
	"pallet-subtensor-swap/runtime-benchmarks",
	"pallet-transaction-payment/runtime-benchmarks",
	"pallet-crowdloan/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"pallet-proxy-opentensor/runtime-benchmarks",
	"pallet-utility-opentensor/runtime-benchmarks"
]
try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"pallet-balances/try-runtime",
	"pallet-evm/try-runtime",
	"pallet-membership/try-runtime",
	"pallet-preimage/try-runtime",
	"pallet-scheduler/try-runtime",
	"pallet-transaction-payment/try-runtime",
	"sp-runtime/try-runtime",
	"pallet-collective/try-runtime",
	"pallet-drand/try-runtime",
	"runtime-common/try-runtime",
	"pallet-aura/try-runtime",
	"pallet-babe/try-runtime",
	"pallet-timestamp/try-runtime",
	"pallet-crowdloan/try-runtime",
	"pallet-proxy-opentensor/try-runtime",
	"pallet-utility-opentensor/try-runtime"
]
pow-faucet = []
fast-runtime = [
	"subtensor-runtime-common/fast-runtime"
]
