[package]
name = "pallet-subtensor-swap-runtime-api"
version = "1.0.0"
description = "Runtime API for the Swap pallet"
edition.workspace = true

[dependencies]
codec = { workspace = true, features = ["derive"] }
scale-info.workspace = true
sp-api.workspace = true
sp-std.workspace = true

[features]
default = ["std"]
std = ["codec/std", "scale-info/std", "sp-api/std", "sp-std/std"]
