[package]
name = "share-pool"
version = "0.1.0"
edition.workspace = true

[dependencies]
substrate-fixed.workspace = true
sp-std.workspace = true
safe-math.workspace = true

[lints]
workspace = true

[features]
default = ["std"]
std = ["substrate-fixed/std", "sp-std/std", "safe-math/std"]
