name: cargo audit
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
concurrency:
  group: cargo-audit-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cargo-audit:
    name: cargo audit
    runs-on: SubtensorCI
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'skip-cargo-audit') }}
    steps:
      - name: Check-out repositoroy under $GITHUB_WORKSPACE
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update &&
          sudo apt-get install -y clang curl libssl-dev llvm libudev-dev protobuf-compiler

      - name: Utilize Shared Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          key: cargo-audit
          cache-on-failure: true

      - name: Install cargo-audit
        run: cargo install --force cargo-audit

      - name: Display cargo-audit --version
        run: cargo audit --version

      - name: cargo audit
        run: |
          cargo audit --ignore RUSTSEC-2023-0091 \
                      --ignore RUSTSEC-2025-0009 \
                      --ignore RUSTSEC-2024-0438
