name: Finney Deploy Check

on:
  pull_request:
    branches: [finney, main]
    types: [labeled, unlabeled, synchronize, opened]

env:
  CARGO_TERM_COLOR: always

jobs:
  check-spec-version:
    name: Check spec_version bump
    runs-on: [self-hosted, type-ccx33]
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'no-spec-version-bump') }}
    steps:
      - name: Dependencies
        run: |
          sudo DEBIAN_FRONTEND=noninteractive NEEDRESTART_MODE=a apt-get update
          sudo DEBIAN_FRONTEND=noninteractive NEEDRESTART_MODE=a apt-get install -y --no-install-recommends -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" build-essential clang curl libssl-dev llvm libudev-dev protobuf-compiler pkg-config

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Check-out repository under $GITHUB_WORKSPACE
        uses: actions/checkout@v4

      - name: Utilize Shared Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          key: try-runtime

      - name: Install substrate-spec-version
        run: cargo install substrate-spec-version

      - name: Check that spec_version has been bumped
        run: |
          spec_version=$(PATH=$PATH:$HOME/.cargo/.bin substrate-spec-version wss://entrypoint-finney.opentensor.ai:443 | tr -d '\n')
          echo "network spec_version: $spec_version"
          : ${spec_version:?bad spec version}
          local_spec_version=$(cargo run -p subtensor-tools --bin spec-version | tr -d '\n')
          echo "local spec_version: $local_spec_version"
          echo "network spec_version: $spec_version"
          if (( $(echo "$local_spec_version <= $spec_version" | bc -l) )); then echo "$local_spec_version ≯ $spec_version ❌"; exit 1; fi
          echo "$local_spec_version > $spec_version ✅"
