[package]
name = "subtensor-macros"
version = "0.1.0"
edition.workspace = true
license = "MIT"

description = "support macros for Subtensor"
repository = "https://github.com/opentensor/subtensor"
homepage = "https://bittensor.com/"

[lib]
proc-macro = true

[dependencies]
syn = { workspace = true, features = [
    "full",
    "visit-mut",
    "visit",
    "extra-traits",
    "parsing",
] }
proc-macro2.workspace = true
quote.workspace = true
ahash.workspace = true

[lints]
workspace = true
